### ISSUE TITLE
Compatibility with $q.all

### ISSUE THREAD

**Issue by demisx** [bendrucker/sinon-as-promised#18]
Hi there. Thank you for putting together a very useful library. One thing I've run into and been struggling with the last two days, is trying to get `$q.all(promises)` resolve when the stubs are resolved in each promise.

I have this method I am testing:

```js
attachPhotoData: function (photos) {
  ... ... ...
  promises.push(fileReader.readAsDataUrl(photo)); // populate with $q promise objects
  return $q.all(promises)
        .then(function (photos) {
          console.log('Resolved collection:', photos); // <- never get here from test
          return photos;
        })
}
```

Everything works fine in the browser, but I have issues in tests where I mock like that:

```js
module(function($provide) {
      $provide.value('fileReader', {
        readAsDataUrl: sinon.stub().resolves('data:image/jpeg;base64,some-photo-data')
      });
    });
```
and a test like this:
```js
it('attaches photo data to each photo', function(done) {
      var photosWithData = postForm.attachPhotoData(photos);
      photosWithData
      .then(function(result) {
        console.log('Resolved photos:', result); // <- never get here
        done();
      });

      $rootScope.$apply();
});
```

It appears that, though the `readAsDataUrl` stub resolves each promise as expected, Angular `$q.all` never gets resolved. Seems like `$q.all` doesn't detect that all `sinon-as-promissed` promises in the `promisses` array have been resolved and my test times out after 2 seconds as it should. Everything works fine if I modify the stub to use `$q.when` instead:

```js
beforeEach(function() {
 ...
  inject(function(_$q_, _$rootScope_, _postForm_, _fileReader_) {
    postForm = _postForm_;
    fileReader = _fileReader_;
    $q = _$q_;
    $rootScope = _$rootScope_;
    fileReader.readAsDataUrl = sinon.stub().returns($q.when('data:image/jpeg;base64,some-photo-data'));
  });
});
```

Wonder, if this is something you've run into before.

**Comment by bendrucker** [comment]
Hmm. So sinon-as-promised as of v2 returns thenables rather than promises. It works pretty much exactly the way knex queries do. There's a method then, but it's not a real promise. Promise implementations are supposed to call `then` anytime a return value has it as a method. 

Can't see any reason why there would be problems:

https://github.com/angular/angular.js/blob/master/src/ng/q.js#L514-L536

Do me favor and write up a reproduction that I can clone and `npm test`. Also make sure you're calling `sinonAsPromised($q)`: https://github.com/bendrucker/sinon-as-promised/blob/master/examples/angular/test.js#L12

**Comment by demisx** [comment]
> Also make sure you're calling sinonAsPromised($q)

Sure enough, I forgot to call this in `beforeEach` block. Everything is working smooth now. Thank you.
