### ISSUE TITLE
Request: sinon method that returns a pending promise

### ISSUE THREAD

**Issue by tjmehta** [bendrucker/sinon-as-promised#35]
Love the module and have found it really useful. I have one feature request so far: I want a way to be able to return an incomplete promise from sinon.

I realize I could easily just return a `Promise` using `returns`, but I would like the convenience of being able to call `resolve` or `reject` external to the `Promise`.

For Example:
```js

var stub = sinon.stub().returnsPromise() // or equivalent

var mockPromise = stub()

mockPromise.then(function (str) {
  console.log('hello')
})

mockPromise.resolves('hello') // rejects should also work
```

What do you think?

**Comment by bendrucker** [comment]
Hmm, interesting idea but I'm not sure how to execute it without a bunch of complexity. In order to do this, you'd either need to mutate the promise object to add a `resolves` method or wrap every method in order to avoid mutation. 

Here's an alternate idea. In order to do what you want, you really need the `Deferred` API or to extract the resolution functions from the resolver. What you could do is this:

```js
var resolve
var promise = new Promise(function (_resolve) {
  resolve = _resolve
})
var stub = sinon.stub().resolves(promise)
var mockPromise = stub()

mockPromise.then(console.log)
resolve('hello')
```

You might consider writing some sort of wrapper for deferred resolution like this. My hesitation to support this is that Sinon asks you to define return/callback values before calling your stubs. Breaking that pattern is awkward and probably best left to either userland or a separate package.

**Comment by tjmehta** [comment]
Cool, I actually ended up doing something similar to what you suggested. Your explanation makes sense. Thanks! 

I will let you know if anything else strikes me, but you can close this issue out

Typed using my thumbs..
