### ISSUE TITLE
sinon 2

### ISSUE THREAD

**Issue by danielbush** [bendrucker/sinon-as-promised#37]
Hi there,
Just wondering how hard it would be to get sinon-as-promised to work with sinon 2 - it's still in "pre" I think, ie version 2.0.0-pre .  I tried running against this version, but ran into trouble with sinon.behaviour .  I guess i could look into it - don't know sinon internals that well.
(Background: I've been having issues with sinon 1 and webpack and loading, so I have some motivation to move to 2).

Thanks for this library,
Cheers,
Daniel

**Comment by bendrucker** [comment]
See #36--it's impossible to create a version that passes tests for v1 and v2. Will have to release a v2 only version once it's truly released.

**Comment by lemieux** [comment]
@danielbush I've been using this bootstrap snippet before my tests 

```
var sinon = require('sinon');
sinon.behavior = require('sinon/lib/sinon/behavior');
sinon.defaultConfig = {
    injectInto: null,
    properties: ['spy', 'stub', 'mock', 'clock', 'server', 'requests'],
    useFakeTimers: true,
    useFakeServer: true
};
require('sinon-as-promised');
```

I'm using sinon@2.0.0-pre and sinon-as-promised@4.0.0 with webpack. Works like a charm.

**Comment by travi** [comment]
with v2.0 being pushed out today, is the snippet above still the recommended approach for getting this working, or is there a plan to release an update soon that would be compatible?

**Comment by tanx** [comment]
> See #36--it's impossible to create a version that passes tests for v1 and v2. Will have to release a v2 only version once it's truly released.

@bendrucker sinon@2.0.0 was released. How about sinon@2.x support in sinon-as-promised@5.0.0 and letting 4.x live on for a while for sinon@1.x support?

Thank you for your time.

**Comment by bendrucker** [comment]
Yup that sounds ok to me @tanx

**Comment by bendrucker** [comment]
I'm happy to review a PR based on the code and comments in #36. I think it's important to retain the nth call behavior even though requiring an undocumented module within a package is generally pretty breakable.

**Comment by fearphage** [comment]
This extension is no longer needed as far as I can tell with Sinon 2.0. It already has this functionality:

sinonjs/sinon#1211

@bendrucker Thanks for your excellent work!

**Comment by bendrucker** [comment]
Excellent, thanks for sharing @fearphage!

I'll leave this open until I have a chance to update the docs w/ this info.

**Comment by bendrucker** [comment]
Thanks to everyone who contributed here! I've added a note to the readme and left the peerDep on sinon@1 to deter usage w/ sinon@2. I've had the pleasure of retiring a bunch of `*-as-promised` libraries over the past year. This package will of course live on as long as npm but shouldn't need any more updates.

This functionality definitely belongs in the library itself, FWIW. I had to rely on returning thenables to avoid unhandled rejection warnings. It was a neat technical exercise (see [create-thenable](https://github.com/bendrucker/create-thenable)) for me. But as a built-in feature, sinon can much more easily just `Promise['resolve' || 'reject']` at invocation time instead of doing fancy things. 

🌮 🌮 🌮 👏 👏 👏
