### ISSUE TITLE
Provide some kind of changelog / release notes

### ISSUE THREAD

**Issue by voxpelli** [bendrucker/sinon-as-promised#43]
When doing a `npm outdated` on ones repo and finding out that there's a new major version of a dependency and then going to that dependency and finding no easy to discover notes at all about what triggered the major update – that makes one a bit more hesitant to upgrade than otherwise and it takes a bit more time than it needs to do.

The combined time spent by maintainers to write a changelog or release notes is surely much less compared to the combined time spent by users of the library trying to figure out what the breaking change is when there aren't any such notes.

It's also in the interest of everyone to have people be on the latest version and discover, test and contribute on that one rather than  have many lag behind on older versions and maybe even, in the worst cases, report bugs that are already fixed.

If one adds release notes to the release tags as well, then one also get an easily subcribeable feed that describes all changes: https://github.com/bendrucker/sinon-as-promised/releases.atom

More thoughts can be found on http://keepachangelog.com/

(And I'm sure you have already given changelog / release notes a thought, but wanted to write down my thoughts anyway)

**Comment by bendrucker** [comment]
Thanks for the suggestion. I think a lot of your comments are right:

> The combined time spent by maintainers to write a changelog or release notes is surely much less compared to the combined time spent by users of the library trying to figure out what the breaking change is when there aren't any such notes.

That's almost certainly true. The alternative everyone gets for free:

https://github.com/bendrucker/sinon-as-promised/compare/v3.0.1...v4.0.0

Those commits could have been a lot neater but they still work—I didn't have to do any extra work or maintain new tooling to get it. 

With 4.0, no breaking source code changes happened at all. It was just removing the build file and cutting off non-npm support. 

I'm actually content making upgrades a bit harder if it leaves me with more time to build things. Changelogs are more valuable for big projects where changes are coordinated more thoughtfully and there's tons of API churn and new bugs. 

For a 35 line library I'm disinclined to do it precisely because I don't mind people being on out of date versions or having reading the log a bit to understand the diffs.

If you have any ideas on how I could add optional notes to git tags, assuming that's visible in releases, I'm totally open to a minor change that doesn't require a totally new workflow/manual step.

**Comment by voxpelli** [comment]
The way I often do it is that I just add the lines of any notable change to my `CHANGELOG.md` and then when I do the release I just set the correct version number in there (or even create all of the notes at the time of release), then copy the changes for that version, remove any markdown formatting and pastes it into the tag notes for that release. I'm sure there's others who have a more automated approach.

For some projects I do have an automated [standard-changelog](https://github.com/conventional-changelog/standard-changelog) based approach instead, but that requires a new workflow and is mostly of benefit in bigger projects with many participants where one wants to enforce some kind of changelog practice, so not something I would suggest for this project.

Not sure how much time you would earn from not writing a changelog. It's very quickly done by someone who knows what changes has been made. Especially when the lines code is very small. (For me as a consumer, I just see the major version bump, not your lines of code)

In this case it sounds like the changelog entry could have been something as small as:

## 4.0.0 

* **Change:** Removed non-npm support
* **Internal:** Refactored the build system

**Comment by bendrucker** [comment]
Right, the problem isn't writing those notes, it's doing it consistently across 400+ public/private packages. If I don't have a tool that pops up an editor and lets me fill these in on every release I'm not going to end up doing it reliably.

**Comment by voxpelli** [comment]
If one wants to get help in writing the changelog, then a tool like https://github.com/semantic-release/semantic-release is probably what one would have to use and then it would probably mean a change in workflow and how one marks up commit messages.

Whether one really has to do it consistently across all projects is another matter. As long as all changes are there and are understandable and it looks okay, that may be enough. It may even be an advantage to have a human touch to it.

As said, I'm undecided myself and mixes the two approaches between my projects.

**Comment by bendrucker** [comment]
Yeah that'd be a massive breaking workflow change I don't want to undertake. Either way I'm pretty lukewarm on doing this in the first place so I'm not going to put time into changing right now.
